spring.application.name=career-tracker

spring.datasource.url=jdbc:mysql://localhost/career
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create

server.servlet.context-path=/api/v1